apiVersion: 1.0.0
metadata:
  name: voting-app-workerdb2-crw
components:
  - id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: venv
        containerPath: /home/jboss/.venv
    alias: python
    # image: 'registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.15'
    image: 'installer.internal.net:5000/l4a/plugin-java8-rhel8:2.15-l4a'
    env:
      - name: REDIS_HOST
        value: new-redis.pdf-voting-app-demo.svc.cluster.local
      - name: REDIS_PASSWORD
        value: admin
      - name: WHICH_DBM # DB2 or POSTGRES
        value: DB2
      - name: DB2_ACCESS # ODBC or REST
        value: ODBC
      - name: DB2_REST_APIURL
        value: ''
      - name: DB2_HOSTNAME
        value: localhost
      - name: DB2_PORT
        value: '50000'
      - name: DB2_DATABASE
        value: SAMPLEDB
      - name: DB2_SCHEMA
        value: team1
      - name: DB2_USER
        value: db2inst1
      - name: DB2_PASSWORD
        value: passw0rd
commands:
  - name: 1. Install requirements
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-workerdb2-crw'
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python -m pip install --upgrade pip && python -m pip install -r requirements.txt
        component: python
  - name: 1. Run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-workerdb2-crw'
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python app.py
        component: python
  - name: Debug current file
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "internalConsole"
              }
            ]
          }
        type: vscode-launch
