apiVersion: 1.0.0
metadata:
  name: voting-app-worker-crw
components:
  - id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: venv
        containerPath: /home/jboss/.venv
    alias: python
    image: 'registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.15'
commands:
  - name: 1. Install requirements
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-worker-crw'
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python -m pip install --upgrade pip && python -m pip install -r requirements.txt
        component: python

  - name: 1. Run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-worker-crw'
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python app.py
        component: python
  - name: Debug current file
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "internalConsole"
              }
            ]
          }
        type: vscode-launch
